# Generated by Django 3.1.7 on 2021-04-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='catalog',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
